services:
  whatsapp-bot:
    build: .
    container_name: gnp_whatsapp_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - baileys_data:/app/baileys_auth
    ports:
      - "54321:54321"

volumes:
  baileys_data: